"""Adding inspection date to establishments.

Revision ID: 0fde7792029d
Revises: 99df941b7556
Create Date: 2019-04-09 16:07:25.051800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fde7792029d'
down_revision = '99df941b7556'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('establishment', sa.Column('inspection_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('establishment', 'inspection_date')
    # ### end Alembic commands ###
