"""establishments table

Revision ID: c13a1bfb1016
Revises: 
Create Date: 2019-04-08 11:53:08.473448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c13a1bfb1016'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('establishment',
    sa.Column('camis', sa.Integer(), nullable=False),
    sa.Column('dba', sa.String(), nullable=True),
    sa.Column('boro', sa.String(), nullable=True),
    sa.Column('building', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('zipcode', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('cuisine', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('camis')
    )
    op.create_index(op.f('ix_establishment_cuisine'), 'establishment', ['cuisine'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_establishment_cuisine'), table_name='establishment')
    op.drop_table('establishment')
    # ### end Alembic commands ###
