"""adding uniqueness constraint to ratings

Revision ID: d904d747cd54
Revises: a9ddbc1d01f7
Create Date: 2019-04-08 19:52:10.735522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd904d747cd54'
down_revision = 'a9ddbc1d01f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'rating', ['camis', 'date'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rating', type_='unique')
    # ### end Alembic commands ###
